'use strict'

const EspoonRadat = [
    {
        "course_id": "2855",
        "name": "Nuuksio, Karhunpesä",
        "holes": "9",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "",
        "latitude": "60.304760",
        "longitude": "24.550881",
        "street_addr": "",
        "reviews": "0",
        "rating": "0.00",
        "private": "1",
        "paytoplay": "1",
        "tee_1_clr": "FF0000",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "0000CC",
        "tee_4_clr": "FFCC00",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2855",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2855",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "2856",
        "name": "Oittaan Ulkoilukartano",
        "holes": "18",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02740",
        "latitude": "60.240243",
        "longitude": "24.662271",
        "street_addr": "Kunnarlantie 33 - 39",
        "reviews": "1",
        "rating": "2.50",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "00FF00",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2856",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2856",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.5.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.5.png"
    },
    {
        "course_id": "8463",
        "name": "Puolarmaarin frisbeegolfrata",
        "holes": "14",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02210",
        "latitude": "60.176613",
        "longitude": "24.697868",
        "street_addr": "Puolarmaari 12",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "FF0000",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "0000CC",
        "tee_4_clr": "FFCC00",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=8463",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=8463",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "10256",
        "name": "Taavinkylä School DiscGolfPark",
        "holes": "3",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02180",
        "latitude": "60.196100",
        "longitude": "24.753000",
        "street_addr": "Taavilantie 19",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10256",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10256",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "10255",
        "name": "Vasikkasaari",
        "holes": "9",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02230",
        "latitude": "60.140600",
        "longitude": "24.758700",
        "street_addr": "Iso Vasikkasaari",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10255",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10255",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    }
]