'use strict'

const radat = [
    {
        "course_id": "2855",
        "name": "Nuuksio, Karhunpesä",
        "holes": "9",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "",
        "latitude": "60.304760",
        "longitude": "24.550881",
        "street_addr": "",
        "reviews": "0",
        "rating": "0.00",
        "private": "1",
        "paytoplay": "1",
        "tee_1_clr": "FF0000",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "0000CC",
        "tee_4_clr": "FFCC00",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2855",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2855",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "2856",
        "name": "Oittaan Ulkoilukartano",
        "holes": "18",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02740",
        "latitude": "60.240243",
        "longitude": "24.662271",
        "street_addr": "Kunnarlantie 33 - 39",
        "reviews": "1",
        "rating": "2.50",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "00FF00",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2856",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2856",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.5.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.5.png"
    },
    {
        "course_id": "8463",
        "name": "Puolarmaarin frisbeegolfrata",
        "holes": "14",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02210",
        "latitude": "60.176613",
        "longitude": "24.697868",
        "street_addr": "Puolarmaari 12",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "FF0000",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "0000CC",
        "tee_4_clr": "FFCC00",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=8463",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=8463",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "10256",
        "name": "Taavinkylä School DiscGolfPark",
        "holes": "3",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02180",
        "latitude": "60.196100",
        "longitude": "24.753000",
        "street_addr": "Taavilantie 19",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10256",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10256",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "10255",
        "name": "Vasikkasaari",
        "holes": "9",
        "city": "Espoo",
        "state": "0",
        "country": "Finland",
        "zipcode": "02230",
        "latitude": "60.140600",
        "longitude": "24.758700",
        "street_addr": "Iso Vasikkasaari",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10255",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10255",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
    {
        "course_id": "9261",
        "name": "Haagan Frisbeegolfrata",
        "holes": "6",
        "city": "Helsinki",
        "state": "0",
        "country": "Finland",
        "zipcode": "00320",
        "latitude": "60.214000",
        "longitude": "24.889600",
        "street_addr": "Isonnevantie",
        "reviews": "1",
        "rating": "0.50",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "FF0000",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "0000CC",
        "tee_4_clr": "FFCC00",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=9261",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=9261",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.5.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.5.png"
    },
        {
            "course_id": "7409",
            "name": "Haagan lähiliikuntapaikka",
            "holes": "6",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "00320",
            "latitude": "60.214000",
            "longitude": "24.889600",
            "street_addr": "Isonnevantie",
            "reviews": "0",
            "rating": "0.00",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=7409",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=7409",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
        },
        {
            "course_id": "5456",
            "name": "Haga Park",
            "holes": "6",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "",
            "latitude": "60.214761",
            "longitude": "24.891565",
            "street_addr": "Isonnevantie 00320",
            "reviews": "1",
            "rating": "0.00",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=5456",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=5456",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
        },
        {
            "course_id": "11215",
            "name": "Kaartin Jääkärirykmentti",
            "holes": "18",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "00860 ",
            "latitude": "60.151300",
            "longitude": "25.054800",
            "street_addr": "Santahamina",
            "reviews": "0",
            "rating": "0.00",
            "private": "1",
            "paytoplay": "1",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=11215",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=11215",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
        },
        {
            "course_id": "5741",
            "name": "Kivikko",
            "holes": "18",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "00940",
            "latitude": "60.238300",
            "longitude": "25.056300",
            "street_addr": "Savikiekontie 8",
            "reviews": "3",
            "rating": "3.17",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=5741",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=5741",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_3.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_3.png"
        },
        {
            "course_id": "2162",
            "name": "Meilahti",
            "holes": "16",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "",
            "latitude": "60.190449",
            "longitude": "24.897487",
            "street_addr": "",
            "reviews": "5",
            "rating": "2.40",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "",
            "tee_3_clr": "",
            "tee_4_clr": "",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2162",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2162",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.5.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.5.png"
        },
        {
            "course_id": "2174",
            "name": "Munkkiniemi",
            "holes": "9",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "",
            "latitude": "60.199846",
            "longitude": "24.869571",
            "street_addr": "",
            "reviews": "2",
            "rating": "0.75",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2174",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2174",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_1.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_1.png"
        },
        {
            "course_id": "2862",
            "name": "Savela",
            "holes": "4",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "",
            "latitude": "60.238597",
            "longitude": "24.998446",
            "street_addr": "",
            "reviews": "1",
            "rating": "0.50",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2862",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2862",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.5.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.5.png"
        },
        {
            "course_id": "2863",
            "name": "Siltamäen frisbeegolfrata",
            "holes": "18",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "00740",
            "latitude": "60.272961",
            "longitude": "24.981837",
            "street_addr": "Pallomäentie",
            "reviews": "3",
            "rating": "2.17",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "",
            "tee_3_clr": "",
            "tee_4_clr": "",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2863",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2863",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.png"
        },
        {
            "course_id": "2161",
            "name": "Talin Huippu",
            "holes": "18",
            "city": "Helsinki",
            "state": "0",
            "country": "Finland",
            "zipcode": "",
            "latitude": "60.213045",
            "longitude": "24.847212",
            "street_addr": "",
            "reviews": "4",
            "rating": "3.88",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2161",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2161",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_4.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_4.png"
        },
        {
        "course_id": "11167",
        "name": "Kartanonkoski ",
        "holes": "9",
        "city": "Vantaa",
        "state": "0",
        "country": "Finland",
        "zipcode": "01520 ",
        "latitude": "60.279200",
        "longitude": "24.956300",
        "street_addr": "TIlkuntie 9",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=11167",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=11167",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
    },
        {
            "course_id": "9264",
            "name": "Malminiityn Frisbeegolfrata",
            "holes": "9",
            "city": "Vantaa",
            "state": "0",
            "country": "Finland",
            "zipcode": "01350",
            "latitude": "60.315800",
            "longitude": "25.041100",
            "street_addr": "Malminiityntie 11",
            "reviews": "1",
            "rating": "1.00",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "",
            "tee_3_clr": "",
            "tee_4_clr": "",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=9264",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=9264",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_1.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_1.png"
        },
        {
            "course_id": "11229",
            "name": "Mikkolan Nuorisotila",
            "holes": "3",
            "city": "Vantaa",
            "state": "0",
            "country": "Finland",
            "zipcode": "01480 ",
            "latitude": "60.341900",
            "longitude": "25.091900",
            "street_addr": "Lyyranpolku",
            "reviews": "0",
            "rating": "0.00",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=11229",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=11229",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
        },
        {
            "course_id": "2923",
            "name": "Päiväkumpu",
            "holes": "10",
            "city": "Vantaa",
            "state": "0",
            "country": "Finland",
            "zipcode": "01420",
            "latitude": "60.325222",
            "longitude": "25.104049",
            "street_addr": "Ilosjoentie",
            "reviews": "1",
            "rating": "2.00",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FF0000",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "0000CC",
            "tee_4_clr": "FFCC00",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2923",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2923",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.png"
        },
        {
            "course_id": "2924",
            "name": "Simonmetsä",
            "holes": "10",
            "city": "Vantaa",
            "state": "0",
            "country": "Finland",
            "zipcode": "01350",
            "latitude": "60.305844",
            "longitude": "25.028486",
            "street_addr": "",
            "reviews": "1",
            "rating": "2.50",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "FFFFFF",
            "tee_2_clr": "",
            "tee_3_clr": "",
            "tee_4_clr": "",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=2924",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=2924",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_2.5.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_2.5.png"
        },
        {
            "course_id": "10258",
            "name": "Varistonniityn",
            "holes": "18",
            "city": "Vantaa",
            "state": "0",
            "country": "Finland",
            "zipcode": "01660",
            "latitude": "60.274000",
            "longitude": "24.821800",
            "street_addr": "Rystypolku 6",
            "reviews": "1",
            "rating": "4.50",
            "private": "0",
            "paytoplay": "0",
            "tee_1_clr": "",
            "tee_2_clr": "FFFFFF",
            "tee_3_clr": "",
            "tee_4_clr": "",
            "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10258",
            "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10258",
            "rating_img": "https://www.dgcoursereview.com/images/rating/discs_4.5.png",
            "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_4.5.png"
        },
        {
        "course_id": "10257",
        "name": "Grani DiscGolfPark",
        "holes": "9",
        "city": "Kauniainen",
        "state": "0",
        "country": "Finland",
        "zipcode": "02700",
        "latitude": "60.216200",
        "longitude": "24.718000",
        "street_addr": "Student Education 11",
        "reviews": "0",
        "rating": "0.00",
        "private": "0",
        "paytoplay": "0",
        "tee_1_clr": "",
        "tee_2_clr": "FFFFFF",
        "tee_3_clr": "",
        "tee_4_clr": "",
        "dgcr_url": "https://www.dgcoursereview.com/course.php?id=10257",
        "dgcr_mobile_url": "https://www.dgcoursereview.com/mobile/course.php?id=10257",
        "rating_img": "https://www.dgcoursereview.com/images/rating/discs_0.png",
        "rating_img_small": "https://www.dgcoursereview.com/images/rating/discs_sm_0.png"
        }
    ]